version: '3'

services:
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./docker/php/php.ini:/etc/php.ini
      - ./docker/httpd/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./docker/mysql/volumes:/var/lib/mysql
      - ./docker/mysql:/tmp/mysql.sock
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/volumes:/var/lib/mysql
      - ./docker/mysql:/var/run/mysqld/mysqld.sock
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions